package org.mercsmavs.frccopilot.profile;

import java.nio.file.Path;

/**
 * CLI for the profile layer.
 *
 * <pre>
 *   init &lt;repoDir&gt; &lt;out.yaml&gt; [team] [robot] [game]   generate a profile from a robot repo
 *   show &lt;profile.yaml&gt;                               print a stored profile
 * </pre>
 */
public final class ProfileCli {

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println(
                    """
                    frc-ai-copilot profile
                    usage:
                      init <repoDir> <out.yaml> [team] [robot] [game]
                      show <profile.yaml>
                    """);
            System.exit(2);
            return;
        }

        switch (args[0]) {
            case "init" -> {
                Path repo = Path.of(args[1]);
                Path out = Path.of(args[2]);
                Integer team = args.length > 3 ? Integer.parseInt(args[3]) : null;
                String robot = args.length > 4 ? args[4] : null;
                String game = args.length > 5 ? args[5] : "REBUILT";
                ProfileBuilder.Result result = ProfileBuilder.fromRepo(repo, team, robot, game);
                String header =
                        "Generated by frc-ai-copilot from " + repo
                                + "\nReview CAN IDs (especially any flagged accurate: false) before use.";
                ProfileMapper.write(result.profile(), out, header);
                System.out.println("Wrote profile: " + out);
                if (!result.warnings().isEmpty()) {
                    System.out.println("Warnings:");
                    result.warnings().forEach(w -> System.out.println("  - " + w));
                }
            }
            case "show" -> {
                RobotProfile p = ProfileMapper.read(Path.of(args[1]));
                System.out.println(ProfileMapper.toYaml(p));
            }
            default -> {
                System.err.println("unknown command: " + args[0]);
                System.exit(2);
            }
        }
    }

    private ProfileCli() {}
}
